// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "Products service API",
    "version": "1"
  },
  "paths": {
    "/products": {
      "get": {
        "summary": "getProductList",
        "description": "",
        "operationId": "getProductList.get.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "The list of products",
            "schema": {
              "$ref": "#/definitions/ProductListResponse"
            }
          },
          "500": {
            "description": "Server error"
          }
        }
      },
      "post": {
        "summary": "createProduct",
        "description": "",
        "operationId": "createProduct.post.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "201": {
            "description": "Product created",
            "schema": {
              "$ref": "#/definitions/ProductResponse"
            }
          },
          "400": {
            "description": "Bad request"
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    },
    "/products/{productId}": {
      "get": {
        "summary": "getProductById",
        "description": "",
        "operationId": "getProductById.get.products/{productId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "productId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Get one single product",
            "schema": {
              "$ref": "#/definitions/ProductResponse"
            }
          },
          "404": {
            "description": "Product not found"
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    },
    "/upload": {
      "get": {
        "summary": "uploadToDB",
        "description": "",
        "operationId": "uploadToDB.get.upload",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "201": {
            "description": "Data uploaded"
          },
          "500": {
            "description": "Server error"
          }
        }
      }
    }
  },
  "definitions": {
    "ProductList": {
      "items": {
        "$ref": "#/definitions/Product"
      },
      "title": "ProductList",
      "type": "array"
    },
    "ProductListResponse": {
      "properties": {
        "products": {
          "$ref": "#/definitions/ProductList",
          "title": "ProductListResponse.products"
        }
      },
      "required": [
        "products"
      ],
      "additionalProperties": false,
      "title": "ProductListResponse",
      "type": "object"
    },
    "Product": {
      "properties": {
        "count": {
          "title": "Product.count",
          "type": "number"
        },
        "description": {
          "title": "Product.description",
          "type": "string"
        },
        "id": {
          "title": "Product.id",
          "type": "string"
        },
        "price": {
          "title": "Product.price",
          "type": "number"
        },
        "title": {
          "title": "Product.title",
          "type": "string"
        }
      },
      "required": [
        "count",
        "description",
        "id",
        "price",
        "title"
      ],
      "additionalProperties": false,
      "title": "Product",
      "type": "object"
    },
    "ProductWithoutCount": {
      "title": "ProductWithoutCount"
    },
    "StockItem": {
      "properties": {
        "product_id": {
          "title": "StockItem.product_id",
          "type": "string"
        },
        "count": {
          "title": "StockItem.count",
          "type": "number"
        }
      },
      "required": [
        "product_id",
        "count"
      ],
      "additionalProperties": false,
      "title": "StockItem",
      "type": "object"
    },
    "ProductResponse": {
      "properties": {
        "product": {
          "$ref": "#/definitions/Product",
          "title": "ProductResponse.product"
        }
      },
      "required": [
        "product"
      ],
      "additionalProperties": false,
      "title": "ProductResponse",
      "type": "object"
    }
  },
  "securityDefinitions": {},
  "basePath": "/dev",
  "host": "b8nbu70yzh.execute-api.eu-west-1.amazonaws.com"
};